<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1/HardwareAcceleration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sat Oct 10 15:43:31 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
cuda_available=torch.cuda.is_available()
cuda_available

True

In [3]:
# no of gpus
torch.cuda.device_count()

1

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name()

'Tesla T4'

In [6]:
memory_allocated_gpu=torch.cuda.memory_allocated(0)
memory_allocated_gpu

0

In [7]:
memory_reserved=torch.cuda.memory_reserved(0)
memory_reserved

0

In [8]:
total_memory=torch.cuda.get_device_properties(0)
total_memory

_CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=14912MB, multi_processor_count=40, uuid=102d14ed-afac-cb88-ff6e-1a0f6cce6fd5, pci_bus_id=0, pci_device_id=4, pci_domain_id=0, L2_cache_size=4MB)

In [9]:
#pytorch version
torch.__version__

'2.11.0+cu130'

In [10]:
#cuda version
torch.version.cuda

'13.0'

In [11]:
#cuDNN version
torch.backends.cudnn.version()

92700

In [12]:
#cuda enabled
torch.backends.cudnn.enabled

True

In [14]:
torch.cuda.device_count()

1

In [16]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [18]:
torch.cuda.device_count()

1

In [20]:
tensor=torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [21]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [23]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [22]:
tensor_on_gpu.to("cpu")

tensor([1, 2, 3])