<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1%5CReproducibilty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reproducibilty

In [8]:
import torch
random_tensor_A= torch.rand(3,4)
print(f"Tensor A :\n{random_tensor_A}")


Tensor A :
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])


In [10]:
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A=torch.rand(3,4)
print(f"Tensor A:\n{random_tensor_A}\n")

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])



In [4]:
import torch
random_seed=42
torch.cuda.manual_seed(seed=random_seed)
random_tensor_A=torch.rand(3,4,device="cuda")
print(f"Tensor A:\n {random_tensor_A}\n")

Tensor A:
 tensor([[0.6130, 0.0101, 0.3984, 0.0403],
        [0.1563, 0.4825, 0.7362, 0.4060],
        [0.5189, 0.2867, 0.2416, 0.9228]], device='cuda:0')

