<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1%5CReshapingTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x=torch.arange(1.,10)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x_reshape=x.reshape(1,9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

* view method doesn't make copy of tensor instead give you another view of the same tensor

In [ ]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

* changing view changes x

In [ ]:
z[:,0] =5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

* stacking tensor on top of eachother

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

* lets remove all single dim from a tensor
` torch.squeeze() `

In [ ]:
print(x_reshape)
x_reshape.shape

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


torch.Size([1, 9])

In [ ]:
x_squeezed=x_reshape.squeeze()
print(x_squeezed)
x_squeezed.shape

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.Size([9])

In [ ]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed.shape)
x_unsqueezed

torch.Size([1, 9])


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

* rearrange the order of axes values with `torch.permute(input,dims)`

In [ ]:
x_original=torch.rand(size=(224,224,3))
print(f"Previous shape: {x_original.shape}")
# rearrage the axis
x_permuted=x_original.permute(2,0,1)
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing

In [ ]:
y=torch.arange(1,10).reshape(1,3,3)
y,y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"First square bracket:\n {y[0]}")
print(f"Second square bracket:\n {y[0][0]}")
print(f"Third square bracket: \n {y[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
 tensor([1, 2, 3])
Third square bracket: 
 1


In [ ]:
y[:,0]

tensor([[1, 2, 3]])

In [ ]:
y[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
y[:,1,1]

tensor([5])

In [ ]:
y[0,0,:]

tensor([1, 2, 3])