<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Manipulation

In [3]:
import torch
import numpy as np
random_tensor=torch.rand(size=(3,4))
random_tensor

tensor([[0.5932, 0.4730, 0.8548, 0.0810],
        [0.8122, 0.8804, 0.0525, 0.9120],
        [0.4041, 0.7034, 0.1507, 0.6551]])

In [4]:
random_tensor.shape

torch.Size([3, 4])

In [5]:
random_tensor.dtype

torch.float32

Statistical properties

In [6]:
torch.min(random_tensor).item()

0.05248075723648071

In [7]:
torch.max(random_tensor).item()

0.9120452404022217

In [8]:
torch.mean(random_tensor).item()

0.5477039813995361

In [9]:
torch.std(random_tensor).item()

0.31513726711273193

In [10]:
theoretical_std=1.0/(12 **0.50)
theoretical_std

0.2886751345948129

Computer vision

In [11]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.1091, 0.5458, 0.0796],
         [0.8521, 0.4851, 0.4257],
         [0.7057, 0.9494, 0.2518],
         ...,
         [0.4592, 0.2273, 0.3122],
         [0.9579, 0.0160, 0.1698],
         [0.0855, 0.0295, 0.3461]],

        [[0.9892, 0.5603, 0.9929],
         [0.0329, 0.8858, 0.6186],
         [0.6770, 0.4750, 0.1481],
         ...,
         [0.9483, 0.1437, 0.9679],
         [0.2715, 0.9717, 0.3802],
         [0.6647, 0.7543, 0.6950]],

        [[0.8871, 0.5325, 0.5065],
         [0.5189, 0.5768, 0.5827],
         [0.8080, 0.8436, 0.6353],
         ...,
         [0.8767, 0.8829, 0.3091],
         [0.4432, 0.0418, 0.7281],
         [0.8327, 0.6808, 0.5953]],

        ...,

        [[0.0994, 0.0936, 0.1324],
         [0.8290, 0.1063, 0.3561],
         [0.1601, 0.1228, 0.9568],
         ...,
         [0.1243, 0.0793, 0.5590],
         [0.6253, 0.3649, 0.5983],
         [0.6964, 0.0015, 0.3544]],

        [[0.0707, 0.5740, 0.4858],
         [0.9862, 0.7016, 0.2890],
         [0.

In [13]:
ele_size=random_image_size_tensor.element_size()

In [16]:
total_memory=random_image_size_tensor.numel() * ele_size
total_memory

602112

In [18]:
#total_memory_usage
total_memory=total_memory/1024/1024
total_memory

5.476176738739014e-07

In [20]:
ten_zeros=torch.zeros_like(torch.arange(0,10,1))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
float_tensor=torch.tensor(
    [3,6,9],dtype=None,device=None,requires_grad=False
)
float_tensor.shape

torch.Size([3])

In [22]:
float_tensor.dtype

torch.int64

In [23]:
float_tensor.device

device(type='cpu')