<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1/TensorBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

print(f"Pytorch version: {torch.__version__}")

Pytorch version: 2.11.0+cpu


In [3]:
scaler_tensor=torch.tensor(7)
print(scaler_tensor)

tensor(7)


In [4]:
vector_tensor=torch.tensor([1,2,3,4,5])
vector_tensor.dim()

1

In [5]:
matrix_tensor=torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix_tensor.dim()

2

In [6]:
tensor_3d=torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
tensor_3d.dim()

3

In [7]:
float_tensor=torch.tensor([1.0,2.0,3.0],dtype=torch.float32)
float_tensor.element_size()

4

In [8]:
float_tensor1=torch.tensor([1.0,2.0,3.0],dtype=torch.float64)
float_tensor1.element_size()

8

In [11]:
boolean_tensor=torch.tensor([1,0,1],dtype=torch.int32)
boolean_tensor.dim()
boolean_tensor.shape

torch.Size([3])

# Creating tensors from numpy arrays

In [13]:
np_array=np.array([[1,2,3],[4,5,6]])

tensor_from_numpy=torch.from_numpy(np_array)
print(f"Numpy array: {np_array} \n dtype: {tensor_from_numpy.dtype}")

Numpy array: [[1 2 3]
 [4 5 6]] 
 dtype: torch.int64


In [15]:
np_array[0,0]=100
print(f"Numpy array:\n{np_array}")
print(f"Pytorch tensor:\n{tensor_from_numpy}")


Numpy array:
[[100   2   3]
 [  4   5   6]]
Pytorch tensor:
tensor([[100,   2,   3],
        [  4,   5,   6]])


# Creating Empty,Ones,Zeros teensors

In [16]:
zero_tensor=torch.zeros(3,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
ones_tensor=torch.ones(2,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
empty_tensor=torch.empty(2,2)
empty_tensor

tensor([[0.2838, 0.0000],
        [0.0000, 0.0000]])

In [19]:
filled_tensor=torch.full((3,2),42)
filled_tensor

tensor([[42, 42],
        [42, 42],
        [42, 42]])

# Creating tensor with sequential values

In [20]:
range_tensor=torch.arange(0,10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
step_tensor=torch.arange(0,10,2)
step_tensor

tensor([0, 2, 4, 6, 8])

In [23]:
linear_tensor=torch.linspace(0,1,5)
linear_tensor

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [24]:
log_tensor=torch.logspace(1,4,5)
log_tensor

tensor([   10.0000,    56.2341,   316.2278,  1778.2794, 10000.0000])

Creating Identity matrices

In [25]:
#identity matrix
identity_matrix=torch.eye(3)
identity_matrix


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
#(2,4) identity matrix
non_square_identity=torch.eye(2,4)
non_square_identity

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])

#Creating Diagonal Matrices

In [27]:
vector=torch.tensor([1,2,3])
diagonal_matrix=torch.diag(vector)

diagonal_matrix

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [28]:
matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
extracted_diagonal=torch.diag(matrix)
extracted_diagonal

tensor([1, 5, 9])