<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/Week1%5CTorch_Np_Integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [8]:
array=np.arange(1.0,9.0)
print(array)
tensor=torch.from_numpy(array)
print(tensor)
tensor.shape

[1. 2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


torch.Size([8])

In [7]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
print(tensor)
print(numpy_tensor)
print(numpy_tensor.shape)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]
(7,)
